setup:
  type: list
  default: 'community, https://mongodb.com/community/forums'
  description: |
    Each line should be in the format of "<code>tag</code>, <code>URL</code>".<br/><br/>
    <ul>
    <li>The tag is the actual tag name, for example /tag/<b>mongodb</b>/</li>
    <li>The URL is whatever URL you wish them to land on once the button is clicked</li>
    </ul>
