settings:
  default: >-
    [{"tag":"about this site","url":"/faq"},
    {"tag":"your preferences","url":"/my/preferences"}]
  json_schema: '{
    "type": "array",
    "format": "table",
    "uniqueItems": true,
    "items": {
      "type": "object",
      "properties": {
        "tag": {
          "type": "string", "minLength": 1
          },
        "url": { "type": "string" }
          },
        "additionalProperties": false
      }
  }'
