setup:
  default: >-
    [{"tag":"about this site","url":"/faq"},
    {"tag":"your preferences","url":"/my/preferences"}]
  json_schema: '{
    "type": "array",
    "format": "table",
    "uniqueItems": true,
    "items": {
      "type": "object",
      "properties": {
        "tag": {
          "type": "string", "minLength": 1
          },
        "url": { "type": "string" }
          },
        "additionalProperties": false
      }
  }'

suffix:
  type: list
  default: '*-mug'
  description: 'This optimises and lessens the load on the theme component loading on every single topic page by adding a the common suffix for tags you want to be checked'